# Generated by Django 4.1.7 on 2023-03-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0003_profile_addresses_profile_favorites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='uf',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
