# Generated by Django 4.1.7 on 2023-03-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0005_alter_city_options_alter_state_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='opening_time',
            field=models.TimeField(),
        ),
    ]
