# Generated by Django 4.1.7 on 2023-03-03 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0007_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
